// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-nwQOT7pEQ4HM1C3bFjpwc8LVSovfL-0',
    appId: '1:496160745435:web:3b6fa9f13958159d6f69fe',
    messagingSenderId: '496160745435',
    projectId: 'doctor-appointment-app-672b2',
    authDomain: 'doctor-appointment-app-672b2.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-672b2.firebasestorage.app',
    measurementId: 'G-99MT1VX6PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpRMOv1jvQbo4tDc_PlgXk9SQQlLIAMRc',
    appId: '1:496160745435:android:9f04ad24b7fb32e66f69fe',
    messagingSenderId: '496160745435',
    projectId: 'doctor-appointment-app-672b2',
    storageBucket: 'doctor-appointment-app-672b2.firebasestorage.app',
  );
}
